//! Insight data structures

#![allow(dead_code)]

use std::time::Instant;

/// Severity level of an insight
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum Severity {
    /// Informational, no action needed
    Info,
    /// Warning, may need attention
    Warning,
    /// Critical, needs immediate attention
    Critical,
}

impl Severity {
    /// Get display string
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Info => "INFO",
            Severity::Warning => "WARN",
            Severity::Critical => "CRIT",
        }
    }

    /// Get icon for display
    pub fn icon(&self) -> &'static str {
        match self {
            Severity::Info => "i",
            Severity::Warning => "!",
            Severity::Critical => "X",
        }
    }
}

/// An insight generated by the analyzer
#[derive(Debug, Clone)]
pub struct Insight {
    /// Unique identifier for deduplication
    pub id: String,
    /// Severity level
    pub severity: Severity,
    /// Associated process PID (None for system-wide)
    pub pid: Option<i32>,
    /// Process name (for display)
    pub process_name: Option<String>,
    /// Short title
    pub title: String,
    /// Detailed explanation
    pub explanation: String,
    /// Suggested action
    pub suggestion: String,
    /// When this insight was generated
    pub timestamp: Instant,
    /// Whether this has been acknowledged by user
    pub acknowledged: bool,
}

impl Insight {
    /// Create a new insight
    pub fn new(
        id: impl Into<String>,
        severity: Severity,
        title: impl Into<String>,
        explanation: impl Into<String>,
        suggestion: impl Into<String>,
    ) -> Self {
        Self {
            id: id.into(),
            severity,
            pid: None,
            process_name: None,
            title: title.into(),
            explanation: explanation.into(),
            suggestion: suggestion.into(),
            timestamp: Instant::now(),
            acknowledged: false,
        }
    }

    /// Set the associated process
    pub fn with_process(mut self, pid: i32, name: impl Into<String>) -> Self {
        self.pid = Some(pid);
        self.process_name = Some(name.into());
        self
    }

    /// Format for single-line display
    pub fn one_line(&self) -> String {
        let prefix = match self.severity {
            Severity::Info => "i",
            Severity::Warning => "!",
            Severity::Critical => "X",
        };

        let target = self
            .process_name
            .as_ref()
            .map(|n| format!("{}: ", n))
            .unwrap_or_default();

        format!("{} {}{}", prefix, target, self.title)
    }

    /// Format for multi-line display
    pub fn detailed(&self) -> String {
        let mut lines = Vec::new();

        let prefix = match self.severity {
            Severity::Info => "[INFO]",
            Severity::Warning => "[WARN]",
            Severity::Critical => "[CRIT]",
        };

        let target = self
            .process_name
            .as_ref()
            .map(|n| format!(" ({})", n))
            .unwrap_or_default();

        lines.push(format!("{}{}: {}", prefix, target, self.title));
        lines.push(format!("  {}", self.explanation));
        lines.push(format!("  -> {}", self.suggestion));

        lines.join("\n")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stable_text_surfaces_include_severity_and_target() {
        let insight = Insight::new(
            "fixture",
            Severity::Warning,
            "High memory",
            "RSS increased",
            "Inspect the process",
        )
        .with_process(42, "worker");
        assert_eq!(insight.one_line(), "! worker: High memory");
        assert_eq!(
            insight.detailed(),
            "[WARN] (worker): High memory\n  RSS increased\n  -> Inspect the process"
        );
        assert_eq!(Severity::Critical.as_str(), "CRIT");
        assert_eq!(Severity::Critical.icon(), "X");
    }
}
